# Generated by Django 3.2.7 on 2023-09-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0002_auto_20230915_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='student_number',
            new_name='id_number',
        ),
    ]
