# Generated by Django 3.2.7 on 2023-09-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0006_delete_medhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=10)),
                ('medication', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('diagnosis', models.CharField(max_length=50)),
            ],
        ),
    ]
