# Generated by Django 3.2.7 on 2023-09-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0007_medhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedHistory',
        ),
    ]
