# Generated by Django 3.2.7 on 2023-09-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0010_alter_medhistory_bp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedHistory',
        ),
    ]
