# Generated by Django 3.2.7 on 2023-09-19 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0012_medhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medhistory',
            name='first_name',
        ),
    ]
