# Generated by Django 3.2.7 on 2023-09-19 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpisApp', '0013_remove_medhistory_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedHistory',
        ),
    ]
